In [1]:
import numpy as np

In [2]:
# Creating array object
arr = np.array( [[ 1, 8, 3],
                 [ 9, 2, 5]] )

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([[1, 8, 3],
       [9, 2, 5]])

In [5]:
arr.ndim

2

In [7]:
arr.shape

(2, 3)

In [8]:
arr.size

6

In [9]:
 arr.dtype

dtype('int32')

In [23]:
a = np.array([[7, 9, 4], [6, 8, 7]], dtype = 'float')

In [11]:
a

array([[7., 9., 4.],
       [6., 8., 7.]])

In [12]:
# can create np array using tupple.

In [13]:
print ("Adding 1 to every element:", a + 1)

Adding 1 to every element: [[ 8. 10.  5.]
 [ 7.  9.  8.]]


In [14]:
 a.sum()

41.0

In [15]:
arr1 = np.array( [[ 9, 8, 1],
                 [ 9, 9, 5]] )

In [16]:
arr1+arr

array([[10, 16,  4],
       [18, 11, 10]])

In [18]:
a.dtype

dtype('float64')

In [19]:
np.sqrt(arr1)

array([[3.        , 2.82842712, 1.        ],
       [3.        , 3.        , 2.23606798]])

In [20]:
c = np.empty([3, 3])

In [22]:
xxa = np.arange(12)

In [25]:
cp = np.zeros([3, 3])

In [28]:
a = a.reshape(3,2)
 

In [29]:
a

array([[7., 9.],
       [4., 6.],
       [8., 7.]])

In [31]:
list1 = [1, 2, 3, 4, 9, 6]
list2 = [10, 9, 3, 7, 6, 5]

a1 = np.array(list1)
a2 = np.array(list2)
 
print(a1*a2)

[10 18  9 28 54 30]


In [32]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
# Index values can be negative.
arr = x[np.array([1, 3, -3])]

In [33]:
arr

array([2, 4, 7])